apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30001
  selector:
    app: flask-app
    tier: frontend
